export interface GenericSPKDetail {
  id: number;
  nama?: string;
  no_pelanggan?: string;
  alamat?: string;
  tanggal?: string; 
  wilayah_id?: number;
  wilayah?: string;
  rayon_id?: number;
  rayon?: string | null;
  kode_rayon?: string | null;
  tglrab?: string;
  no_rab?: string;
  reg_id?: number;
  no_hp?: string;
  no_telp?: string;
  email?: string;
  jenis_bangunan?: string;
  kepemilikan?: string;
  latitude?: string | null;
  longitude?: string | null;
  keterangan?: string | null;
  biaya_peralatan?: number;
  biaya_ongkos?: number;
  biaya_survey?: number;
  biaya_jl?: string | number;
  biaya_lainnya?: number;
  diskon?: number;
  ppn?: number;
  total?: number;
  no_regis?: string;
  kec_id?: number | null;
  kecamatan?: string | null;
  kelurahan?: string | null;
  jenis?: string; 
  jenis_nonair_id?: number;
  namajenis?: string; 
  kec?: string; 
  kel?: string;
  diameter?: string;
  merek_meter?: string | null;
  biaya_bukasegel?: string | number;
  no_aduan?: string;
  jenis_aduan?: string;
  ket_aduan?: string;
  url_foto_aduan?: string | null;
  url_foto_penyelesaian?: string | null;
  completed_at?: string | null;
}